/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.46
 * Generated at: 2025-10-22 23:33:27 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class facture_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');

    request.setCharacterEncoding("UTF-8");

    double qte1 = Double.parseDouble(request.getParameter("qte1"));
    double qte2 = Double.parseDouble(request.getParameter("qte2"));
    double qte3 = Double.parseDouble(request.getParameter("qte3"));
    double prix1 = Double.parseDouble(request.getParameter("prix1"));
    double prix2 = Double.parseDouble(request.getParameter("prix2"));
    double prix3 = Double.parseDouble(request.getParameter("prix3"));
    double remise = Double.parseDouble(request.getParameter("remise"));

    double totalHT1 = qte1 * prix1;
    double totalHT2 = qte2 * prix2;
    double totalHT3 = qte3 * prix3;
    double totalNetHT = totalHT1 + totalHT2 + totalHT3;
    double tva = totalNetHT * 0.20;
    double totalTTC = totalNetHT + tva - remise;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <title>Facture Détails</title>\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("</head>\n");
      out.write("<body class=\"bg-dark text-white\">\n");
      out.write("<div class=\"container mt-5 p-4 bg-secondary rounded shadow\">\n");
      out.write("    <h3 class=\"text-center text-warning mb-4\">Détails de la Facture</h3>\n");
      out.write("\n");
      out.write("    <p><strong>Numéro :</strong> ");
      out.print( request.getParameter("numFacture") );
      out.write("</p>\n");
      out.write("    <p><strong>Client :</strong> ");
      out.print( request.getParameter("nomClient") );
      out.write("</p>\n");
      out.write("    <p><strong>Email :</strong> ");
      out.print( request.getParameter("emailClient") );
      out.write("</p>\n");
      out.write("\n");
      out.write("    <table class=\"table table-bordered table-dark\">\n");
      out.write("        <thead>\n");
      out.write("            <tr>\n");
      out.write("                <th>Description</th>\n");
      out.write("                <th>Qté</th>\n");
      out.write("                <th>Prix Unitaire</th>\n");
      out.write("                <th>Total HT</th>\n");
      out.write("            </tr>\n");
      out.write("        </thead>\n");
      out.write("        <tbody>\n");
      out.write("            <tr><td>Macbook Pro M2</td><td>");
      out.print( qte1 );
      out.write("</td><td>");
      out.print( prix1 );
      out.write("</td><td>");
      out.print( totalHT1 );
      out.write("</td></tr>\n");
      out.write("            <tr><td>Imprimante HP 7740</td><td>");
      out.print( qte2 );
      out.write("</td><td>");
      out.print( prix2 );
      out.write("</td><td>");
      out.print( totalHT2 );
      out.write("</td></tr>\n");
      out.write("            <tr><td>Disque SSD 500GO</td><td>");
      out.print( qte3 );
      out.write("</td><td>");
      out.print( prix3 );
      out.write("</td><td>");
      out.print( totalHT3 );
      out.write("</td></tr>\n");
      out.write("        </tbody>\n");
      out.write("    </table>\n");
      out.write("\n");
      out.write("    <div class=\"text-end\">\n");
      out.write("        <p><strong>Total net HT :</strong> ");
      out.print( totalNetHT );
      out.write(" DH</p>\n");
      out.write("        <p><strong>TVA (20%) :</strong> ");
      out.print( tva );
      out.write(" DH</p>\n");
      out.write("        <p><strong>Remise :</strong> ");
      out.print( remise );
      out.write(" DH</p>\n");
      out.write("        <h5 class=\"text-warning\">Total TTC : ");
      out.print( totalTTC );
      out.write(" DH</h5>\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
