/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.46
 * Generated at: 2025-10-22 23:32:44 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("    \n");

    // Génération d’un numéro de facture aléatoire entre 1 et 1000
    int number = (int)(Math.random() * 1000) + 1;
    String value = "FA-" + number;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"fr\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <title>Formulaire Facture Client</title>\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("    <style>\n");
      out.write("        body {\n");
      out.write("            background-color: #f8f9fa;\n");
      out.write("            padding: 30px;\n");
      out.write("        }\n");
      out.write("        .facture-header {\n");
      out.write("            margin-bottom: 20px;\n");
      out.write("        }\n");
      out.write("        .table thead {\n");
      out.write("            background-color: #3d8bcc;\n");
      out.write("            color: white;\n");
      out.write("        }\n");
      out.write("        .table tbody tr td:first-child {\n");
      out.write("            font-weight: 600;\n");
      out.write("            color: #2b4c2b;\n");
      out.write("        }\n");
      out.write("        .total-section {\n");
      out.write("            margin-top: 30px;\n");
      out.write("        }\n");
      out.write("        .total-box {\n");
      out.write("            border: 1px solid #dee2e6;\n");
      out.write("            padding: 10px;\n");
      out.write("            background-color: white;\n");
      out.write("        }\n");
      out.write("    </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("<div class=\"container bg-white p-4 shadow rounded\">\n");
      out.write("    <h3 class=\"text-center mb-4\">Formulaire de Facture Client</h3>\n");
      out.write("\n");
      out.write("    <form action=\"facture.jsp\" method=\"post\">\n");
      out.write("\n");
      out.write("        <!-- Informations client -->\n");
      out.write("        <div class=\"row facture-header\">\n");
      out.write("            <div class=\"col-md-4\">\n");
      out.write("                <label class=\"form-label\">Nom Client :</label>\n");
      out.write("                <input type=\"text\" name=\"nomClient\" class=\"form-control\" required>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"col-md-4\">\n");
      out.write("                <label class=\"form-label\">Adresse Client :</label>\n");
      out.write("                <input type=\"text\" name=\"adresseClient\" class=\"form-control\" required>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"col-md-4\">\n");
      out.write("                <label class=\"form-label\">Email Client :</label>\n");
      out.write("                <input type=\"email\" name=\"emailClient\" class=\"form-control\" required>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <!-- Numéro de facture -->\n");
      out.write("        <div class=\"d-flex justify-content-end mb-3\">\n");
      out.write("            <div class=\"d-flex align-items-center\">\n");
      out.write("                <label class=\"form-label me-2 mb-0\">Facture N° :</label>\n");
      out.write("                <input type=\"text\" name=\"numeroFacture\" value=\"");
      out.print( value );
      out.write("\" class=\"form-control\" style=\"width:150px;\" readonly>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <!-- Tableau des produits -->\n");
      out.write("        <table class=\"table table-bordered\">\n");
      out.write("            <thead class=\"text-center\">\n");
      out.write("                <tr>\n");
      out.write("                    <th>Description</th>\n");
      out.write("                    <th>Qté</th>\n");
      out.write("                    <th>Prix Unitaire</th>\n");
      out.write("                    <th>Total HT</th>\n");
      out.write("                </tr>\n");
      out.write("            </thead>\n");
      out.write("            <tbody>\n");
      out.write("                <tr>\n");
      out.write("                    <td>Ordinateur portable, Macbook Pro M2</td>\n");
      out.write("                    <td><input type=\"number\" name=\"qte1\" class=\"form-control\" min=\"0\"></td>\n");
      out.write("                    <td><input type=\"number\" name=\"prix1\" class=\"form-control\" min=\"0\" step=\"0.01\"></td>\n");
      out.write("                    <td><input type=\"text\" name=\"total1\" class=\"form-control\" readonly></td>\n");
      out.write("                </tr>\n");
      out.write("                <tr>\n");
      out.write("                    <td>Imprimante HP Pro 7740</td>\n");
      out.write("                    <td><input type=\"number\" name=\"qte2\" class=\"form-control\" min=\"0\"></td>\n");
      out.write("                    <td><input type=\"number\" name=\"prix2\" class=\"form-control\" min=\"0\" step=\"0.01\"></td>\n");
      out.write("                    <td><input type=\"text\" name=\"total2\" class=\"form-control\" readonly></td>\n");
      out.write("                </tr>\n");
      out.write("                <tr>\n");
      out.write("                    <td>Disque dur SSD 500GO</td>\n");
      out.write("                    <td><input type=\"number\" name=\"qte3\" class=\"form-control\" min=\"0\"></td>\n");
      out.write("                    <td><input type=\"number\" name=\"prix3\" class=\"form-control\" min=\"0\" step=\"0.01\"></td>\n");
      out.write("                    <td><input type=\"text\" name=\"total3\" class=\"form-control\" readonly></td>\n");
      out.write("                </tr>\n");
      out.write("            </tbody>\n");
      out.write("        </table>\n");
      out.write("\n");
      out.write("        <!-- Conditions et Totaux -->\n");
      out.write("        <div class=\"row total-section\">\n");
      out.write("            <div class=\"col-md-6\">\n");
      out.write("                <h6 class=\"fw-bold\">Conditions de paiement</h6>\n");
      out.write("                <p>\n");
      out.write("                    Les modes de paiement acceptés incluent le chèque, le virement bancaire\n");
      out.write("                    et la carte de crédit.\n");
      out.write("                </p>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"col-md-6\">\n");
      out.write("                <div class=\"total-box\">\n");
      out.write("                    <div class=\"d-flex justify-content-between\">\n");
      out.write("                        <span>Total net HT :</span>\n");
      out.write("                        <input type=\"text\" name=\"totalHT\" class=\"form-control text-end\" style=\"width:120px;\" readonly>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"d-flex justify-content-between mt-2\">\n");
      out.write("                        <span>TVA :</span>\n");
      out.write("                        <input type=\"number\" name=\"tva\" class=\"form-control text-end\" style=\"width:120px;\">\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"d-flex justify-content-between mt-2\">\n");
      out.write("                        <span>Remise :</span>\n");
      out.write("                        <input type=\"number\" name=\"remise\" class=\"form-control text-end\" style=\"width:120px;\">\n");
      out.write("                    </div>\n");
      out.write("                    <hr>\n");
      out.write("                    <div class=\"d-flex justify-content-between fw-bold\">\n");
      out.write("                        <span>Total TTC :</span>\n");
      out.write("                        <input type=\"text\" name=\"totalTTC\" class=\"form-control text-end\" style=\"width:120px;\" value=\"0.00 DH\" readonly>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <!-- Boutons -->\n");
      out.write("        <div class=\"text-center mt-4\">\n");
      out.write("            <button type=\"submit\" class=\"btn btn-success px-4\">Soumettre</button>\n");
      out.write("            <button type=\"reset\" class=\"btn btn-secondary px-4\">Annuler</button>\n");
      out.write("        </div>\n");
      out.write("    </form>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
